from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Dict, Any


class SearchHit(BaseModel):
    id: str = Field(description="Unique identifier for the search hit")
    title: str = Field(description="Title of the document or chunk")
    content: str = Field(description="Content of the document or chunk")
    url: str = Field(description="URL of the document")
    score: float = Field(description="Relevance score of the search hit")
    metadata: Dict[str, Any] = Field(default_factory=dict)


class GeneratorResponse(BaseModel):
    query: str = Field(description="The original search query")
    summary: Optional[str] = Field(description="Summary generated by the LLM")
    results: List[SearchHit] = Field(description="List of search results")
    total: int = Field(description="Total number of search results")
    duration_ms: float = Field(description="Time taken in milliseconds")
